### PR TITLE
sample_data_control

### PR DESCRIPTION
**Pull request by Kev1CO**
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/bioptim/6)

### CODE REVIEW

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioptim/6)* status: all files reviewed, 3 unresolved discussions (waiting on @Kev1CO)

___
*[`bioptim/dynamics/integrator.py` line 73 at r3](https://reviewable.io/reviews/Ipuch/bioptim/6#-NOWbNg0CVJK_ZMME-9m:-NOWbNg0CVJK_ZMME-9n:b-wedw6r) ([raw file](https://github.com/Ipuch/bioptim/blob/2a0c91c98677cf1c9dc328fd6cfde7f1aa7e0f2d/bioptim/dynamics/integrator.py#L73)):*
> ```Python
>         self.cx = ode_opt["cx"]
>         self.x_sym = ode["x_scaled"]
>         if ode["implicit_ode"] is not None:
> ```

This is not the right if condition. It should be something like: 
```python if "p_scale" in ode.keys(): ```
___
*[`bioptim/dynamics/ode_solver.py` line 132 at r3](https://reviewable.io/reviews/Ipuch/bioptim/6#-NOWbi4T9utry7x6rXwO:-NOWbi4T9utry7x6rXwP:b8161vf) ([raw file](https://github.com/Ipuch/bioptim/blob/2a0c91c98677cf1c9dc328fd6cfde7f1aa7e0f2d/bioptim/dynamics/ode_solver.py#L132)):*
> ```Python
>                 "x_unscaled": nlp.states.cx,
>                 "x_scaled": nlp.states["scaled"].cx,
>                 "p_unscaled": nlp.controls.cx
> ```

assign p_scale and p_unscale outside of the if condition

```python3

            ode = {
                "x_unscaled": nlp.states.cx,
                "x_scaled": nlp.states["scaled"].cx,
                "ode": nlp.dynamics_func,
                "implicit_ode": nlp.implicit_dynamics_func,
            }

if not isinstance(ocp.nlp[0].dynamics_func, list):
    ode["p_scaled] = ...
    ode["p_unscaled] = ...

```

but maybe the if should be testing the shape of nlp.controls.shape ??? it should be more clean.
___
*[`external/acados` line 1 at r3](https://reviewable.io/reviews/Ipuch/bioptim/6#-NOWcbl997idftfzYN4H:-NOWcbl997idftfzYN4I:b-4r7ztc) ([raw file](https://github.com/Ipuch/bioptim/blob/fbf7398495fb9b35a0bb65d82df945607ee1db8a/external/acados#L1)):*
> ```
> Subproject commit 8fe9950ce5ceb4f325587719e8cae6aa1b25e4ae
> ```

Ouch, NEVER PUSH ACADOS...., we need to restore it :'(



_Code quote:_
```
5
```

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioptim/6)* status: all files reviewed, 13 unresolved discussions (waiting on @Kev1CO)

___
*[`bioptim/dynamics/integrator.py` line 73 at r3](https://reviewable.io/reviews/Ipuch/bioptim/6#-NOWbNg0CVJK_ZMME-9m:-NP3pEQB0pNG78YTMIzV:bvasy5h) ([raw file](https://github.com/Ipuch/bioptim/blob/2a0c91c98677cf1c9dc328fd6cfde7f1aa7e0f2d/bioptim/dynamics/integrator.py#L73)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This is not the right if condition. It should be something like: 
```python if "p_scale" in ode.keys(): ```

</blockquote></details>

Follow up
___
*[`bioptim/dynamics/ode_solver.py` line 132 at r3](https://reviewable.io/reviews/Ipuch/bioptim/6#-NOWbi4T9utry7x6rXwO:-NP3pkva27KzeUE28Hbb:b32w74) ([raw file](https://github.com/Ipuch/bioptim/blob/2a0c91c98677cf1c9dc328fd6cfde7f1aa7e0f2d/bioptim/dynamics/ode_solver.py#L132)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

assign p_scale and p_unscale outside of the if condition

```python3

            ode = {
                "x_unscaled": nlp.states.cx,
                "x_scaled": nlp.states["scaled"].cx,
                "ode": nlp.dynamics_func,
                "implicit_ode": nlp.implicit_dynamics_func,
            }

if not isinstance(ocp.nlp[0].dynamics_func, list):
    ode["p_scaled] = ...
    ode["p_unscaled] = ...

```

but maybe the if should be testing the shape of nlp.controls.shape ??? it should be more clean.
</blockquote></details>

Up
___
*[`bioptim/dynamics/ode_solver.py` line 118 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3pb5_6mcqDhTrzi3I:-NP3pb5aDsDyBGvhEDZG:ba6r9ah) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/dynamics/ode_solver.py#L118)):*
> ```Python
> 
>         ode_opt = {
>             "t0": nlp.t0,
> ```

Restore
___
*[`bioptim/dynamics/ode_solver.py` line 123 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3pcHt87owId0eodXh:-NP3pcHt87owId0eodXi:ba6r9ah) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/dynamics/ode_solver.py#L123)):*
> ```Python
>             "param": nlp.parameters,
>             "cx": nlp.cx,
>             "idx": nlp.phase_idx,
> ```

Restore
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 341 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3pyo_3iDnyTHyShh7:-NP3pyo_3iDnyTHyShh8:b1n5a7v) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/interfaces/solve_ivp_interface.py#L341)):*
> ```Python
>     dynamics_output = "xall" if keep_intermediate_points else "xf"
> 
>     if len(x0.shape) != len(u.shape) and len(x0.shape) < 2:  # NOT SURE OF THIS FIX
> ```

Comment to remove by the end of the PR if nothing changes.
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 355 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3qVPt3zxgvRCGWrFy:-NP3qVPt3zxgvRCGWrFz:b-rtqgto) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/interfaces/solve_ivp_interface.py#L355)):*
> ```Python
>         else:
>             u_controls = u
>         y = np.concatenate(
> ```

outside of the loop:

```python3 
if not u:
     u_controls = []
else:
     u_slice = slice(s, s + 1) if control_type == ControlType.CONSTANT else slice(s, s + 2)
      u_controls = u[:, u_slice]
  # y always contains [x0, xf] of the interval
```
___
*[`bioptim/optimization/optimal_control_program.py` line 461 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3rtyfEjWvnVEOS5Fn:-NP3rtyg60vrD9k7KtWw:b-ey9pzu) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimal_control_program.py#L461)):*
> ```Python
>         NLP.add(self, "phase_mapping", phase_mapping, True)
>         NLP.add(self, "dof_names", dof_names, True)
>         # todo : finalement pas un pb pour le model step3
> ```

remove comment.
___
*[`bioptim/optimization/optimization_variable.py` line 483 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3ry2d3bXKFXXkZUtx:-NP3ry2d3bXKFXXkZUty:b-a27n7l) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimization_variable.py#L483)):*
> ```Python
>         """
> 
>         return self._cx[:, 0] if self.shape !=0 else []
> ```

test without
___
*[`bioptim/optimization/optimization_variable.py` line 491 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3s0KqD6gginsikGJV:-NP3s0KqD6gginsikGJW:b-a27n7l) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimization_variable.py#L491)):*
> ```Python
>         """
> 
>         return self._cx_end[:, 0] if self.shape !=0 else []
> ```

test without
___
*[`bioptim/optimization/optimization_variable.py` line 658 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3s0oQ9X369y3Lz3Es:-NP3s0oQ9X369y3Lz3Et:b-a27n7l) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimization_variable.py#L658)):*
> ```Python
>         """
> 
>         return self.optimization_variable["unscaled"].cx if self.shape != 0 else []
> ```

test without
___
*[`bioptim/optimization/optimization_vector.py` line 313 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3sOqqEWQVnjcWCSig:-NP3sOqrDl73BaGb3NHJ:bc582hj) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimization_vector.py#L313)):*
> ```Python
>         for p in range(self.ocp.n_phases):
>             if self.ocp.nlp[p].use_controls_from_phase_idx == self.ocp.nlp[p].phase_idx:
>                 if len(v_array[offset : offset + self.n_phase_u[p]]) != 0:
> ```

put the condition if just after the for p in range(....)
test the size of u (self.n_all_u) if empty or 0, skip the block.
___
*[`bioptim/optimization/solution.py` line 1018 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3t3To-Eh65rICXAzC:-NP3t3To-Eh65rICXAzD:b3i302g) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/solution.py#L1018)):*
> ```Python
>             x0 = self._get_first_frame_states(out, shooting_type, phase=p)
>             if self._controls["unscaled"][controls_phase_idx] == {}:
>                 u = np.array([])
> ```

self._controls.shape ???   instead self._controls["unscaled"][controls_phase_idx] == {} 

"u = XXXX if .... else XXXX"

**Comment by Kev1CO** [comment]
https://github.com/Ipuch/bioptim/blob/fe0d8c04621d8fc06f608b58132b602156931e7b/bioptim/dynamics/integrator.py#L8-L25

Allow u_sym to be a empty list as well ?

**Review by Kev1CO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioptim/6)* status: 0 of 15 files reviewed, 13 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/dynamics/integrator.py` line 73 at r3](https://reviewable.io/reviews/Ipuch/bioptim/6#-NOWbNg0CVJK_ZMME-9m:-NP47arz56EeLsdujXFW:b-896fix) ([raw file](https://github.com/Ipuch/bioptim/blob/2a0c91c98677cf1c9dc328fd6cfde7f1aa7e0f2d/bioptim/dynamics/integrator.py#L73)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Follow up
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 132 at r3](https://reviewable.io/reviews/Ipuch/bioptim/6#-NOWbi4T9utry7x6rXwO:-NP498fABeI-FKUu2Fq1:b5hg4y7) ([raw file](https://github.com/Ipuch/bioptim/blob/2a0c91c98677cf1c9dc328fd6cfde7f1aa7e0f2d/bioptim/dynamics/ode_solver.py#L132)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Up
</blockquote></details>

Done.

Did not find in file ode_solver :
if not isinstance(ocp.nlp[0].dynamics_func, list):
    ode["p_scaled] = ...
    ode["p_unscaled] = ...

in order to assign p_scale and p_unscale outside of the if condition
___
*[`bioptim/dynamics/ode_solver.py` line 118 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3pb5_6mcqDhTrzi3I:-NP47wYu2aBQVmFaWBvj:b9dozci) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/dynamics/ode_solver.py#L118)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Restore
</blockquote></details>

Done.
For odd reasons works better that way "t0": 0
___
*[`bioptim/dynamics/ode_solver.py` line 123 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3pcHt87owId0eodXh:-NP48CfN4kQe5NvDv-Gm:bd75253) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/dynamics/ode_solver.py#L123)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Restore
</blockquote></details>

Done.
For odd reasons works better that way "idx": 0
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 355 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3qVPt3zxgvRCGWrFy:-NP4BCON3b3NAY5yILdj:bf9i25q) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/interfaces/solve_ivp_interface.py#L355)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

outside of the loop:

```python3 
if not u:
     u_controls = []
else:
     u_slice = slice(s, s + 1) if control_type == ControlType.CONSTANT else slice(s, s + 2)
      u_controls = u[:, u_slice]
  # y always contains [x0, xf] of the interval
```


</blockquote></details>

Done. Wrote if expression better

Don't understand how to move u_control out of the loop as the slice method depends on the func iterated in the for loop
___
*[`bioptim/optimization/optimal_control_program.py` line 461 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3rtyfEjWvnVEOS5Fn:-NP4Bmbc-LwDWIuncVbj:b-896fix) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimal_control_program.py#L461)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove comment.
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_variable.py` line 483 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3ry2d3bXKFXXkZUtx:-NP4E6VqCK20AH0BAGvq:bfkim24) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimization_variable.py#L483)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

test without
</blockquote></details>

Cannot remove the if condition as if the user ask all_pn.nlp.controls["scaled"].cx it crashes
Done.

Was only able to remove one of them in the clas OptimizationVariableContainer
___
*[`bioptim/optimization/optimization_variable.py` line 491 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3s0KqD6gginsikGJV:-NP4Dpjf4tHtMUqYoDmp:bukptk0) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimization_variable.py#L491)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

test without
</blockquote></details>

Cannot remove the if condition as if the user ask all_pn.nlp.controls["scaled"].cx_end it crashes
Done.
___
*[`bioptim/optimization/optimization_variable.py` line 658 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3s0oQ9X369y3Lz3Es:-NP4F5Ed4ggY9Ksz5s1F:bw6jbm6) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimization_variable.py#L658)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

test without
</blockquote></details>

Done.
For some odd reasons it disappeared since the push
___
*[`bioptim/optimization/optimization_vector.py` line 313 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3sOqqEWQVnjcWCSig:-NP4GFGW6g4sVelYy5cc:b-896fix) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/optimization_vector.py#L313)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

put the condition if just after the for p in range(....)
test the size of u (self.n_all_u) if empty or 0, skip the block.
</blockquote></details>

Done.
___
*[`bioptim/optimization/solution.py` line 1018 at r5](https://reviewable.io/reviews/Ipuch/bioptim/6#-NP3t3To-Eh65rICXAzC:-NP4HHlF1Aotwf-Ux7T1:b-896fix) ([raw file](https://github.com/Ipuch/bioptim/blob/c12176aa12353044f6ecb6d1afd9cb1f38f7b77e/bioptim/optimization/solution.py#L1018)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

self._controls.shape ???   instead self._controls["unscaled"][controls_phase_idx] == {} 

"u = XXXX if .... else XXXX"
</blockquote></details>

Done.
___
*[`external/acados` line 1 at r3](https://reviewable.io/reviews/Ipuch/bioptim/6#-NOWcbl997idftfzYN4H:-NP4GIonA8o8vcYbAb0O:b-896fix) ([raw file](https://github.com/Ipuch/bioptim/blob/fbf7398495fb9b35a0bb65d82df945607ee1db8a/external/acados#L1)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Ouch, NEVER PUSH ACADOS...., we need to restore it :'(
</blockquote></details>

Done.

**Pull request merged**
